name: Release
on:
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
      - run: yarn reset
      - run: yarn changeset version
      - id: readver
        run: echo "v=$(node -p \"require('./package.json').version\")" >> "$GITHUB_OUTPUT"
      - run: yarn build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Push version & changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet && echo "No changes" || git commit -m "chore: release v${{ steps.readver.outputs.v }}"
          git push
      - name: Create & push tag
        run: |
          VER="v${{ steps.readver.outputs.v }}"
          if git rev-parse -q --verify "refs/tags/$VER" >/dev/null; then
            echo "Tag $VER already exists, skipping"
          else
            git tag "$VER"
            git push origin "$VER"
          fi
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.readver.outputs.v }}
          name: v${{ steps.readver.outputs.v }}
          body: |
            See CHANGELOG.md for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
